const GET_DOWNLOADS = 'GET_DOWNLOADS';
const ERROR = 'ERROR';
const SET_TIME_RANGE = 'SET_TIME_RANGE';
const TIME_DIFFERENCE = 'TIME_DIFFERENCE';
export {
  GET_DOWNLOADS, ERROR, SET_TIME_RANGE, TIME_DIFFERENCE,
};
